### PR TITLE
support exec scp local dir to remote

### PR DESCRIPTION
**Pull request by oldthreefeng**
[SKIP CI]seaols: 一句话简短描述该PR内容

1. 重新写了一下scp, 每次复制文件都复用`sftpClient`. 
2. 支持传输文件夹.

### CODE REVIEW

**Comment by cuisongliu** [comment]
尽量加一下测试用例。简单写一下。

**Comment by oldthreefeng** [comment]
测试日志如下:  应该算是初步实现了. 没有进行压力测试. 

<details><summary><code>1. scp dir Output logs</code> </summary><br><pre>
~]# ./sealos  exec --cmd "hostname -i" --src /root/temp --dst /data/temp  --label node-role.kubernetes.io/master=
13:35:31 [INFO] [ssh.go:12] [ssh][192.168.160.243:22] hostname
13:35:31 [DEBG] [ssh.go:24] [ssh][192.168.160.243:22]command result is: dev-k8s-master
13:35:31 [INFO] [scp.go:328] [ssh]transfer [/root/temp/Dockerfile] total size is: 0.33KB ;speed is 0KB
13:35:31 [INFO] [scp.go:328] [ssh]transfer [/root/temp/harbor.yaml] total size is: 6.09KB ;speed is 6KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/hello-contour.yaml] total size is: 10.10KB ;speed is 10KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/helloworld.yaml] total size is: 10.19KB ;speed is 10KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/httpbin.yaml] total size is: 1.46KB ;speed is 1KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/istio.yaml] total size is: 624.26KB ;speed is 624KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/keycloak.yaml] total size is: 10.11KB ;speed is 10KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/kubeadm-config.yaml] total size is: 1.11KB ;speed is 1KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/kuboard.yaml] total size is: 2.24KB ;speed is 2KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/test01/harbor.yaml] total size is: 6.09KB ;speed is 6KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/test01/hello-contour.yaml] total size is: 10.10KB ;speed is 10KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/test01/helloworld.yaml] total size is: 10.19KB ;speed is 10KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/test01/httpbin.yaml] total size is: 1.46KB ;speed is 1KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/test01/istio.yaml] total size is: 624.26KB ;speed is 624KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/test01/keycloak.yaml] total size is: 10.11KB ;speed is 10KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/test01/kubeadm-config.yaml] total size is: 1.11KB ;speed is 1KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/test01/kuboard.yaml] total size is: 2.24KB ;speed is 2KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/test02/harbor.yaml] total size is: 6.09KB ;speed is 6KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/test02/hello-contour.yaml] total size is: 10.10KB ;speed is 10KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/test02/helloworld.yaml] total size is: 10.19KB ;speed is 10KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/test02/httpbin.yaml] total size is: 1.46KB ;speed is 1KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/test02/istio.yaml] total size is: 624.26KB ;speed is 624KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/test02/keycloak.yaml] total size is: 10.11KB ;speed is 10KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/test02/kubeadm-config.yaml] total size is: 1.11KB ;speed is 1KB
13:35:32 [INFO] [scp.go:328] [ssh]transfer [/root/temp/test02/kuboard.yaml] total size is: 2.24KB ;speed is 2KB
13:35:32 [INFO] [ssh.go:57] [ssh][192.168.160.243:22] cd /tmp && hostname -i
13:35:32 [INFO] [ssh.go:50] [192.168.160.243:22] 192.168.160.243
</pre></details>
<details><summary><code>2. if remote fileExist Output logs</code> </summary><br><pre>
~]# ./sealos  exec --cmd "hostname -i" --src /root/temp --dst /data/temp  --label node-role.kubernetes.io/master=
13:53:06 [INFO] [ssh.go:12] [ssh][192.168.160.243:22] hostname
13:53:06 [DEBG] [ssh.go:24] [ssh][192.168.160.243:22]command result is: dev-k8s-master

13:53:06 [INFO] [ssh.go:12] [ssh][192.168.160.243:22] ls -l /data/temp 2>/dev/null |wc -l
13:53:06 [DEBG] [ssh.go:24] [ssh][192.168.160.243:22]command result is: 12

13:53:06 [INFO] [exec.go:178] [/data/temp] is exist on remote host [192.168.160.243:22].skip...
13:53:06 [INFO] [ssh.go:57] [ssh][192.168.160.243:22] cd /tmp && hostname -i
13:53:07 [INFO] [ssh.go:50] [192.168.160.243:22] 192.168.160.243

</pre></details>

**Comment by oldthreefeng** [comment]
@cuisongliu  推荐一下测试用例哇~  我这边仅仅测试了几条命令.
et....
```
./sealos  exec --cmd "hostname -i" --src /root/temp --dst /data/temp  --label node-role.kubernetes.io/master=
./sealos  exec --cmd "hostname -i" --src /root/temp --dst /data/temp  --node 192.168.160.243
```

**Comment by cuisongliu** [comment]
一般来说是是这样的
https://github.com/fanux/sealos/blob/4ca9a56430175e27b21e9acb9cc14e550c3dd262/install/utils_test.go#L82

测过就OK 我先合入了

**Comment by cuisongliu** [comment]
贴一下测试日志也可以。

**Comment by oldthreefeng** [comment]
ok， 以后我多写test用例~

**Pull request merged**
